// Generated by msgbuf from 'test/ts/explicit/explicit.proto'. Do not edit.
//
// Type definitions for the msgbuf JSON format of the protocol (types only, no runtime code).

import type { DisplayMode, Leaf } from '../test/ts/common/common';

/**
 * A message placed in an explicitly configured module.
 */
export interface Explicit {
	/**
	 * Mode.
	 */
	mode?: DisplayMode;

	/**
	 * Leaves.
	 */
	leaves?: Leaf[];
}
