// Generated by msgbuf from 'test/ts/explicit/explicit.proto'. Do not edit.
//
// Type definitions for the msgbuf JSON format of the protocol (types only, no runtime code).

import type { DisplayModeJson, LeafJson } from '../test/ts/common/common';

/**
 * A message placed in an explicitly configured module.
 */
export interface ExplicitJson {
	/**
	 * Mode.
	 */
	mode: DisplayModeJson;

	/**
	 * Leaves.
	 */
	leaves: LeafJson[];
}
