/*
 * Copyright (c) 2022 Bernhard Haumacher et al. All Rights Reserved.
 */
package de.haumacher.msgbuf.generator;

import java.util.List;
import java.util.Map;
import java.util.Set;

import de.haumacher.msgbuf.generator.ast.Field;
import de.haumacher.msgbuf.generator.ast.MessageDef;
import de.haumacher.msgbuf.generator.ast.Option;
import de.haumacher.msgbuf.generator.util.FileGenerator;

/**
 * Plug-in to the {@link MessageGenerator}.
 */
public interface GeneratorPlugin {

	/**
	 * Initializes the plug-in with file options.
	 * 
	 * @param options The options of the current file to translate.
	 */
	default void init(Map<String, Option> options) {
		// Ignore.
	}
	
	/**
	 * Adds interfaces to the generated type.
	 *
	 * @param options
	 *        The options from the top-level definition file.
	 * @param def
	 *        The {@link MessageDef} that is being translated.
	 * @param generalizations
	 *        The generalization list to extend.
	 */
	default void addInterfaces(Map<String, Option> options, MessageDef def, List<String> generalizations) {
		// No additional interfaces by default.
	}

	/** 
	 * Creates a {@link FileGenerator} that is expanded within the interface class.
	 * 
	 * @param options The options from the top-level definition file.
	 * @param def The {@link MessageDef} that is being translated.
	 */
	default FileGenerator messageInterfaceContents(Map<String, Option> options, MessageDef def) {
		return (out, indent) -> {/*ignore*/};
	}
	
	/** 
	 * Creates a {@link FileGenerator} that is expanded within the implementation class.
	 * 
	 * @param options The options from the top-level definition file.
	 * @param def The {@link MessageDef} that is being translated.
	 */
	default FileGenerator messageImplContents(Map<String, Option> options, MessageDef def) {
		return (out, indent) -> {/*ignore*/};
	}

	/**
	 * Adds the names of the serialization formats this plug-in generates code for.
	 *
	 * <p>
	 * A message referencing a message of another file requires all formats of its own file in the
	 * other file, since its generated code calls the other message's generated read and write
	 * methods.
	 * </p>
	 *
	 * @param options
	 *        The options of a definition file.
	 * @param formats
	 *        The set of format names to add to.
	 */
	default void addFormats(Map<String, Option> options, Set<String> formats) {
		// No additional formats by default.
	}

	/**
	 * Adds the names of the serialization formats in which the code generated by this plug-in
	 * writes and reads the value of the given field.
	 *
	 * <p>
	 * If the field references a message or enum of another file, that file must generate code for
	 * these formats.
	 * </p>
	 *
	 * @param options
	 *        The options of the file defining the field.
	 * @param field
	 *        The field to check.
	 * @param formats
	 *        The set of format names to add to.
	 *
	 * @see #addFormats(Map, Set)
	 */
	default void addFieldFormats(Map<String, Option> options, Field field, Set<String> formats) {
		// No additional formats by default.
	}

	/**
	 * Adds the identifiers of the given concrete message in polymorphic values of the formats of
	 * this plug-in.
	 *
	 * <p>
	 * The generator rejects two concrete specializations of an abstract message with the same
	 * identifier, since the readers of the abstract message cannot distinguish them.
	 * </p>
	 *
	 * @param options
	 *        The options of the file defining the message.
	 * @param def
	 *        The concrete message.
	 * @param typeIds
	 *        The identifiers to add to, indexed by a description of the identifier that names the
	 *        annotation that sets it, e.g. <code>"XML element name (@XmlName)"</code>.
	 */
	default void addTypeIds(Map<String, Option> options, MessageDef def, Map<String, String> typeIds) {
		// No additional identifiers by default.
	}

	/** 
	 * {@link GeneratorPlugin} that does not generate any output.
	 */
	static GeneratorPlugin none() {
		return new GeneratorPlugin() {
			@Override
			public GeneratorPlugin andThen(GeneratorPlugin next) {
				return next;
			}
		};
	}

	/** 
	 * Joins this {@link GeneratorPlugin} with the given one.
	 */
	default GeneratorPlugin andThen(GeneratorPlugin next) {
		GeneratorPlugin self = this;
		
		return new GeneratorPlugin() {
			@Override
			public void init(Map<String, Option> options) {
				self.init(options);
				next.init(options);
			}
			
			@Override
			public void addInterfaces(Map<String, Option> options, MessageDef def, List<String> generalizations) {
				self.addInterfaces(options, def, generalizations);
				next.addInterfaces(options, def, generalizations);
			}

			@Override
			public void addFormats(Map<String, Option> options, Set<String> formats) {
				self.addFormats(options, formats);
				next.addFormats(options, formats);
			}

			@Override
			public void addFieldFormats(Map<String, Option> options, Field field, Set<String> formats) {
				self.addFieldFormats(options, field, formats);
				next.addFieldFormats(options, field, formats);
			}

			@Override
			public void addTypeIds(Map<String, Option> options, MessageDef def, Map<String, String> typeIds) {
				self.addTypeIds(options, def, typeIds);
				next.addTypeIds(options, def, typeIds);
			}
			
			@Override
			public FileGenerator messageImplContents(Map<String, Option> options, MessageDef def) {
				return (out, indent) -> {
					self.messageImplContents(options, def).generate(out, indent);
					next.messageImplContents(options, def).generate(out, indent);
				};
			}
			
			@Override
			public FileGenerator messageInterfaceContents(Map<String, Option> options, MessageDef def) {
				return (out, indent) -> {
					self.messageInterfaceContents(options, def).generate(out, indent);
					next.messageInterfaceContents(options, def).generate(out, indent);
				};
			}
		};
	}

}
