// Generated by msgbuf from 'test/ts/commands/commands.proto'. Do not edit.
//
// Type definitions for the msgbuf JSON format of the protocol, and helper functions for its
// type-tagged polymorphic values (visitor dispatch, tagging, tag guards).

/**
 * Commands for testing the TypeScript helpers of polymorphic values in a closed hierarchy.
 *
 * @packageDocumentation
 */

/**
 * Root of a closed hierarchy.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface CommandJson {
	/**
	 * The command ID.
	 */
	id: string;
}

/**
 * Polymorphic JSON representation of a {@link CommandJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyCommandJson = ['Script', ScriptJson] | ['Batch', BatchJson] | ['Batch.Item', BatchJson.Item] | ['Macro', MacroJson] | ['Insert', InsertJson] | ['delete', deleteJson] | ['Macro.Item', MacroJson.Item] | ['Bold', BoldJson] | ['Replace', ReplaceJson];

/**
 * Handlers for all concrete types of {@link CommandJson}.
 */
export interface CommandJsonVisitor<R> {
	/**
	 * Handles a {@link ScriptJson}.
	 */
	visitScript(self: ScriptJson): R;

	/**
	 * Handles a {@link BatchJson}.
	 */
	visitBatch(self: BatchJson): R;

	/**
	 * Handles a {@link BatchJson.Item}.
	 */
	visitBatch_Item(self: BatchJson.Item): R;

	/**
	 * Handles a {@link MacroJson}.
	 */
	visitMacro(self: MacroJson): R;

	/**
	 * Handles a {@link InsertJson}.
	 */
	visitInsert(self: InsertJson): R;

	/**
	 * Handles a {@link deleteJson}.
	 */
	visitDelete(self: deleteJson): R;

	/**
	 * Handles a {@link MacroJson.Item}.
	 */
	visitMacro_Item(self: MacroJson.Item): R;

	/**
	 * Handles a {@link BoldJson}.
	 */
	visitBold(self: BoldJson): R;

	/**
	 * Handles a {@link ReplaceJson}.
	 */
	visitReplace(self: ReplaceJson): R;
}

/**
 * Dispatches a type-tagged {@link AnyCommandJson} value to the handler of its concrete type.
 *
 * @throws Error if the type ID is not known.
 */
export function visitCommandJson<R>(value: AnyCommandJson, visitor: CommandJsonVisitor<R>): R {
	switch (value[0]) {
		case 'Script': return visitor.visitScript(value[1]);
		case 'Batch': return visitor.visitBatch(value[1]);
		case 'Batch.Item': return visitor.visitBatch_Item(value[1]);
		case 'Macro': return visitor.visitMacro(value[1]);
		case 'Insert': return visitor.visitInsert(value[1]);
		case 'delete': return visitor.visitDelete(value[1]);
		case 'Macro.Item': return visitor.visitMacro_Item(value[1]);
		case 'Bold': return visitor.visitBold(value[1]);
		case 'Replace': return visitor.visitReplace(value[1]);
		default: {
			const unknownType: never = value[0];
			throw new Error('Unknown type ID: ' + unknownType);
		}
	}
}

/**
 * Checks whether the given value is a type-tagged {@link AnyCommandJson} value: a tuple of a known type ID and an object.
 *
 * Only the type ID and the shape of the tuple are checked, not the properties of the object.
 */
export function isAnyCommandJson(value: unknown): value is AnyCommandJson {
	return Array.isArray(value) && value.length === 2
		&& (value[0] === 'Script' || value[0] === 'Batch' || value[0] === 'Batch.Item' || value[0] === 'Macro' || value[0] === 'Insert' || value[0] === 'delete' || value[0] === 'Macro.Item' || value[0] === 'Bold' || value[0] === 'Replace')
		&& typeof value[1] === 'object' && value[1] !== null && !Array.isArray(value[1]);
}

/**
 * Abstract intermediate at level two.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface EditJson extends CommandJson {
	/**
	 * The edited element.
	 */
	target: string;
}

/**
 * Polymorphic JSON representation of a {@link EditJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyEditJson = ['Insert', InsertJson] | ['delete', deleteJson] | ['Macro.Item', MacroJson.Item] | ['Bold', BoldJson] | ['Replace', ReplaceJson];

/**
 * Handlers for all concrete types of {@link EditJson}.
 */
export interface EditJsonVisitor<R> {
	/**
	 * Handles a {@link InsertJson}.
	 */
	visitInsert(self: InsertJson): R;

	/**
	 * Handles a {@link deleteJson}.
	 */
	visitDelete(self: deleteJson): R;

	/**
	 * Handles a {@link MacroJson.Item}.
	 */
	visitMacro_Item(self: MacroJson.Item): R;

	/**
	 * Handles a {@link BoldJson}.
	 */
	visitBold(self: BoldJson): R;

	/**
	 * Handles a {@link ReplaceJson}.
	 */
	visitReplace(self: ReplaceJson): R;
}

/**
 * Dispatches a type-tagged {@link AnyEditJson} value to the handler of its concrete type.
 *
 * @throws Error if the type ID is not known.
 */
export function visitEditJson<R>(value: AnyEditJson, visitor: EditJsonVisitor<R>): R {
	switch (value[0]) {
		case 'Insert': return visitor.visitInsert(value[1]);
		case 'delete': return visitor.visitDelete(value[1]);
		case 'Macro.Item': return visitor.visitMacro_Item(value[1]);
		case 'Bold': return visitor.visitBold(value[1]);
		case 'Replace': return visitor.visitReplace(value[1]);
		default: {
			const unknownType: never = value[0];
			throw new Error('Unknown type ID: ' + unknownType);
		}
	}
}

/**
 * Checks whether the given value is a type-tagged {@link AnyEditJson} value: a tuple of a known type ID and an object.
 *
 * Only the type ID and the shape of the tuple are checked, not the properties of the object.
 */
export function isAnyEditJson(value: unknown): value is AnyEditJson {
	return Array.isArray(value) && value.length === 2
		&& (value[0] === 'Insert' || value[0] === 'delete' || value[0] === 'Macro.Item' || value[0] === 'Bold' || value[0] === 'Replace')
		&& typeof value[1] === 'object' && value[1] !== null && !Array.isArray(value[1]);
}

/**
 * Abstract intermediate at level three.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface StyledEditJson extends EditJson {
	/**
	 * The style to apply.
	 */
	style: string;
}

/**
 * Polymorphic JSON representation of a {@link StyledEditJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyStyledEditJson = ['Bold', BoldJson];

/**
 * Handlers for all concrete types of {@link StyledEditJson}.
 */
export interface StyledEditJsonVisitor<R> {
	/**
	 * Handles a {@link BoldJson}.
	 */
	visitBold(self: BoldJson): R;
}

/**
 * Dispatches a type-tagged {@link AnyStyledEditJson} value to the handler of its concrete type.
 *
 * @throws Error if the type ID is not known.
 */
export function visitStyledEditJson<R>(value: AnyStyledEditJson, visitor: StyledEditJsonVisitor<R>): R {
	switch (value[0]) {
		case 'Bold': return visitor.visitBold(value[1]);
		default: {
			const unknownType: never = value[0];
			throw new Error('Unknown type ID: ' + unknownType);
		}
	}
}

/**
 * Checks whether the given value is a type-tagged {@link AnyStyledEditJson} value: a tuple of a known type ID and an object.
 *
 * Only the type ID and the shape of the tuple are checked, not the properties of the object.
 */
export function isAnyStyledEditJson(value: unknown): value is AnyStyledEditJson {
	return Array.isArray(value) && value.length === 2
		&& value[0] === 'Bold'
		&& typeof value[1] === 'object' && value[1] !== null && !Array.isArray(value[1]);
}

/**
 * A concrete edit at level three.
 */
export interface InsertJson extends EditJson {
	text: string;
}

/**
 * Creates the type-tagged JSON representation of a {@link InsertJson}.
 */
export function tagInsert(self: InsertJson): ['Insert', InsertJson] {
	return ['Insert', self];
}

/**
 * A concrete type specializing a concrete type.
 */
export interface ReplaceJson extends InsertJson {
	length: number;
}

/**
 * Creates the type-tagged JSON representation of a {@link ReplaceJson}.
 */
export function tagReplace(self: ReplaceJson): ['Replace', ReplaceJson] {
	return ['Replace', self];
}

/**
 * A concrete edit at level four.
 */
export interface BoldJson extends StyledEditJson {}

/**
 * Creates the type-tagged JSON representation of a {@link BoldJson}.
 */
export function tagBold(self: BoldJson): ['Bold', BoldJson] {
	return ['Bold', self];
}

/**
 * A message whose name is a reserved word in TypeScript.
 */
export interface deleteJson extends EditJson {
	count: number;
}

/**
 * Creates the type-tagged JSON representation of a {@link deleteJson}.
 */
export function tagDelete(self: deleteJson): ['delete', deleteJson] {
	return ['delete', self];
}

/**
 * A message with polymorphic collections.
 */
export interface ScriptJson extends CommandJson {
	/**
	 * A polymorphic list.
	 */
	steps: AnyCommandJson[];

	/**
	 * A polymorphic map.
	 */
	named: Record<string, AnyCommandJson>;

	/**
	 * A polymorphic map with a key that is not a string.
	 */
	numbered: Array<{ key: number; value: AnyEditJson }>;

	/**
	 * An optional polymorphic value of an intermediate.
	 */
	style?: AnyStyledEditJson;
}

/**
 * Creates the type-tagged JSON representation of a {@link ScriptJson}.
 */
export function tagScript(self: ScriptJson): ['Script', ScriptJson] {
	return ['Script', self];
}

/**
 * Container of a nested message named like one in {@link MacroJson}.
 */
export interface BatchJson extends CommandJson {
	/**
	 * Monomorphic references.
	 */
	items: BatchJson.Item[];
}

export namespace BatchJson {
	/**
	 * Nested specialization of the root.
	 */
	export interface Item extends CommandJson {
		note: string;
	}
}

/**
 * Creates the type-tagged JSON representation of a {@link BatchJson}.
 */
export function tagBatch(self: BatchJson): ['Batch', BatchJson] {
	return ['Batch', self];
}

/**
 * Creates the type-tagged JSON representation of a {@link BatchJson.Item}.
 */
export function tagBatch_Item(self: BatchJson.Item): ['Batch.Item', BatchJson.Item] {
	return ['Batch.Item', self];
}

/**
 * Container of a nested message named like one in {@link BatchJson}, and of a nested hierarchy.
 */
export interface MacroJson extends CommandJson {
	/**
	 * Steps of the nested hierarchy.
	 */
	steps: MacroJson.AnyStep[];

	/**
	 * Items of the intermediate.
	 */
	edits: AnyEditJson[];
}

export namespace MacroJson {
	/**
	 * Nested specialization of an intermediate.
	 */
	export interface Item extends EditJson {
		repeat: number;
	}

	/**
	 * Root of a nested hierarchy.
	 *
	 * Abstract type, the properties are only present in the JSON of its concrete specializations.
	 */
	export interface Step {}

	/**
	 * Polymorphic JSON representation of a {@link Step}: a tuple of the type ID and the properties of a concrete type.
	 */
	export type AnyStep = ['Wait', MacroJson.Wait] | ['Group.Wait', MacroJson.Group.Wait];

	/**
	 * Specialization in the nested hierarchy.
	 */
	export interface Wait extends MacroJson.Step {
		millis: number;
	}

	/**
	 * Specialization in the nested hierarchy nested in another nested message.
	 */
	export interface Group {}

	export namespace Group {
		/**
		 * Needs a type ID different from the one of {@link MacroJson.Wait}.
		 */
		export interface Wait extends MacroJson.Step {
			count: number;
		}
	}
}

/**
 * Creates the type-tagged JSON representation of a {@link MacroJson}.
 */
export function tagMacro(self: MacroJson): ['Macro', MacroJson] {
	return ['Macro', self];
}

/**
 * Creates the type-tagged JSON representation of a {@link MacroJson.Item}.
 */
export function tagMacro_Item(self: MacroJson.Item): ['Macro.Item', MacroJson.Item] {
	return ['Macro.Item', self];
}

/**
 * Handlers for all concrete types of {@link MacroJson.Step}.
 */
export interface Macro_StepJsonVisitor<R> {
	/**
	 * Handles a {@link MacroJson.Wait}.
	 */
	visitMacro_Wait(self: MacroJson.Wait): R;

	/**
	 * Handles a {@link MacroJson.Group.Wait}.
	 */
	visitMacro_Group_Wait(self: MacroJson.Group.Wait): R;
}

/**
 * Dispatches a type-tagged {@link MacroJson.AnyStep} value to the handler of its concrete type.
 *
 * @throws Error if the type ID is not known.
 */
export function visitMacro_StepJson<R>(value: MacroJson.AnyStep, visitor: Macro_StepJsonVisitor<R>): R {
	switch (value[0]) {
		case 'Wait': return visitor.visitMacro_Wait(value[1]);
		case 'Group.Wait': return visitor.visitMacro_Group_Wait(value[1]);
		default: {
			const unknownType: never = value[0];
			throw new Error('Unknown type ID: ' + unknownType);
		}
	}
}

/**
 * Checks whether the given value is a type-tagged {@link MacroJson.AnyStep} value: a tuple of a known type ID and an object.
 *
 * Only the type ID and the shape of the tuple are checked, not the properties of the object.
 */
export function isAnyMacro_StepJson(value: unknown): value is MacroJson.AnyStep {
	return Array.isArray(value) && value.length === 2
		&& (value[0] === 'Wait' || value[0] === 'Group.Wait')
		&& typeof value[1] === 'object' && value[1] !== null && !Array.isArray(value[1]);
}

/**
 * Creates the type-tagged JSON representation of a {@link MacroJson.Wait}.
 */
export function tagMacro_Wait(self: MacroJson.Wait): ['Wait', MacroJson.Wait] {
	return ['Wait', self];
}

/**
 * Creates the type-tagged JSON representation of a {@link MacroJson.Group.Wait}.
 */
export function tagMacro_Group_Wait(self: MacroJson.Group.Wait): ['Group.Wait', MacroJson.Group.Wait] {
	return ['Group.Wait', self];
}

/**
 * An abstract root without concrete types.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface EmptyJson {}

/**
 * Polymorphic JSON representation of a {@link EmptyJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyEmptyJson = never;

/**
 * Handlers for all concrete types of {@link EmptyJson}.
 */
export interface EmptyJsonVisitor<R> {}

/**
 * Dispatches a type-tagged {@link AnyEmptyJson} value to the handler of its concrete type.
 *
 * @throws Error if the type ID is not known.
 */
export function visitEmptyJson<R>(value: AnyEmptyJson, visitor: EmptyJsonVisitor<R>): R {
	switch (value[0]) {
		default: {
			const unknownType: never = value[0];
			throw new Error('Unknown type ID: ' + unknownType);
		}
	}
}

/**
 * Checks whether the given value is a type-tagged {@link AnyEmptyJson} value: a tuple of a known type ID and an object.
 *
 * Only the type ID and the shape of the tuple are checked, not the properties of the object.
 */
export function isAnyEmptyJson(value: unknown): value is AnyEmptyJson {
	// No concrete type is known.
	return false;
}

/**
 * Concrete root of a hierarchy without type tags: no helpers.
 */
export interface PlainJson {
	name: string;
}

/**
 * Specialization of a concrete root: no helpers.
 */
export interface FancyJson extends PlainJson {
	color: string;
}

/**
 * An abstract message below a concrete root: no helpers.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface AbstractedJson extends PlainJson {}
