// Generated by msgbuf from 'test/ts/events/ext/ext.proto'. Do not edit.
//
// Type definitions for the msgbuf JSON format of the protocol, and helper functions for its
// type-tagged polymorphic values (visitor dispatch, tagging, tag guards).

/**
 * Extensions of the OpenWorld hierarchy of another file.
 *
 * @packageDocumentation
 */

import type { ChangeJson, EventJson } from '../base/base';

/**
 * Specialization of the intermediate of another file.
 */
export interface RemoveJson extends ChangeJson {}

/**
 * Creates the type-tagged JSON representation of a {@link RemoveJson}.
 */
export function tagRemove(self: RemoveJson): ['Remove', RemoveJson] {
	return ['Remove', self];
}

/**
 * An abstract intermediate of the extension file.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface NoticeJson extends EventJson {
	text: string;
}

/**
 * Polymorphic JSON representation of a {@link NoticeJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyNoticeJson = ['Alert', AlertJson] | [string, NoticeJson];

/**
 * Handlers for all concrete types of {@link NoticeJson}.
 *
 * The hierarchy is open (option OpenWorld), a type not known to this module is handled by {@link NoticeJsonVisitor.visitDefault}.
 */
export interface NoticeJsonVisitor<R> {
	/**
	 * Handles a {@link AlertJson}.
	 */
	visitAlert(self: AlertJson): R;

	/**
	 * Handles a type that is not known to this module, e.g. an extension defined in another module.
	 *
	 * @param self - The properties of the value.
	 * @param typeId - The type ID of the value.
	 */
	visitDefault(self: NoticeJson, typeId: string): R;
}

/**
 * Dispatches a type-tagged {@link AnyNoticeJson} value to the handler of its concrete type.
 *
 * A type ID not known to this module is dispatched to {@link NoticeJsonVisitor.visitDefault}.
 */
export function visitNoticeJson<R>(value: AnyNoticeJson, visitor: NoticeJsonVisitor<R>): R {
	switch (value[0]) {
		case 'Alert': return visitor.visitAlert(value[1] as AlertJson);
		default: return visitor.visitDefault(value[1], value[0]);
	}
}

/**
 * Checks whether the given value is a type-tagged {@link AnyNoticeJson} value: a tuple of a type ID and an object.
 *
 * Only the type ID and the shape of the tuple are checked, not the properties of the object.
 */
export function isAnyNoticeJson(value: unknown): value is AnyNoticeJson {
	return Array.isArray(value) && value.length === 2
		&& typeof value[0] === 'string'
		&& typeof value[1] === 'object' && value[1] !== null && !Array.isArray(value[1]);
}

/**
 * Specialization of the local intermediate.
 */
export interface AlertJson extends NoticeJson {
	level: number;
}

/**
 * Creates the type-tagged JSON representation of a {@link AlertJson}.
 */
export function tagAlert(self: AlertJson): ['Alert', AlertJson] {
	return ['Alert', self];
}

/**
 * Outer message of a nested extension.
 */
export interface OuterJson {
	notices: AnyNoticeJson[];
}

export namespace OuterJson {
	/**
	 * A nested extension named like a type of the base file.
	 */
	export interface Ping extends EventJson {}
}

/**
 * Creates the type-tagged JSON representation of a {@link OuterJson.Ping}.
 */
export function tagOuter_Ping(self: OuterJson.Ping): ['Outer.Ping', OuterJson.Ping] {
	return ['Outer.Ping', self];
}
