// Generated by msgbuf from 'test/ts/events/base/base.proto'. Do not edit.
//
// Type definitions for the msgbuf JSON format of the protocol, and helper functions for its
// type-tagged polymorphic values (visitor dispatch, tagging, tag guards).

/**
 * An OpenWorld hierarchy extended in another file.
 *
 * @packageDocumentation
 */

import type { OuterJson, RemoveJson, AlertJson } from '../ext/ext';

/**
 * Root of an open hierarchy.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface EventJson {
	/**
	 * Time of the event.
	 */
	timestamp: number;
}

/**
 * Polymorphic JSON representation of a {@link EventJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyEventJson = ['Ping', PingJson] | ['Outer.Ping', OuterJson.Ping] | ['set', UpdateJson] | ['Remove', RemoveJson] | ['Alert', AlertJson] | [string, EventJson];

/**
 * Handlers for all concrete types of {@link EventJson}.
 *
 * The hierarchy is open (option OpenWorld), a type not known to this module is handled by {@link EventJsonVisitor.visitDefault}.
 */
export interface EventJsonVisitor<R> {
	/**
	 * Handles a {@link PingJson}.
	 */
	visitPing(self: PingJson): R;

	/**
	 * Handles a {@link OuterJson.Ping}.
	 */
	visitOuter_Ping(self: OuterJson.Ping): R;

	/**
	 * Handles a {@link UpdateJson}.
	 */
	visitUpdate(self: UpdateJson): R;

	/**
	 * Handles a {@link RemoveJson}.
	 */
	visitRemove(self: RemoveJson): R;

	/**
	 * Handles a {@link AlertJson}.
	 */
	visitAlert(self: AlertJson): R;

	/**
	 * Handles a type that is not known to this module, e.g. an extension defined in another module.
	 *
	 * @param self - The properties of the value.
	 * @param typeId - The type ID of the value.
	 */
	visitDefault(self: EventJson, typeId: string): R;
}

/**
 * Dispatches a type-tagged {@link AnyEventJson} value to the handler of its concrete type.
 *
 * A type ID not known to this module is dispatched to {@link EventJsonVisitor.visitDefault}.
 */
export function visitEventJson<R>(value: AnyEventJson, visitor: EventJsonVisitor<R>): R {
	switch (value[0]) {
		case 'Ping': return visitor.visitPing(value[1] as PingJson);
		case 'Outer.Ping': return visitor.visitOuter_Ping(value[1] as OuterJson.Ping);
		case 'set': return visitor.visitUpdate(value[1] as UpdateJson);
		case 'Remove': return visitor.visitRemove(value[1] as RemoveJson);
		case 'Alert': return visitor.visitAlert(value[1] as AlertJson);
		default: return visitor.visitDefault(value[1], value[0]);
	}
}

/**
 * Checks whether the given value is a type-tagged {@link AnyEventJson} value: a tuple of a type ID and an object.
 *
 * Only the type ID and the shape of the tuple are checked, not the properties of the object.
 */
export function isAnyEventJson(value: unknown): value is AnyEventJson {
	return Array.isArray(value) && value.length === 2
		&& typeof value[0] === 'string'
		&& typeof value[1] === 'object' && value[1] !== null && !Array.isArray(value[1]);
}

/**
 * A local concrete type.
 */
export interface PingJson extends EventJson {}

/**
 * Creates the type-tagged JSON representation of a {@link PingJson}.
 */
export function tagPing(self: PingJson): ['Ping', PingJson] {
	return ['Ping', self];
}

/**
 * An abstract intermediate, extended in another file.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface ChangeJson extends EventJson {
	/**
	 * The changed key.
	 */
	key: string;
}

/**
 * Polymorphic JSON representation of a {@link ChangeJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyChangeJson = ['set', UpdateJson] | ['Remove', RemoveJson] | [string, ChangeJson];

/**
 * Handlers for all concrete types of {@link ChangeJson}.
 *
 * The hierarchy is open (option OpenWorld), a type not known to this module is handled by {@link ChangeJsonVisitor.visitDefault}.
 */
export interface ChangeJsonVisitor<R> {
	/**
	 * Handles a {@link UpdateJson}.
	 */
	visitUpdate(self: UpdateJson): R;

	/**
	 * Handles a {@link RemoveJson}.
	 */
	visitRemove(self: RemoveJson): R;

	/**
	 * Handles a type that is not known to this module, e.g. an extension defined in another module.
	 *
	 * @param self - The properties of the value.
	 * @param typeId - The type ID of the value.
	 */
	visitDefault(self: ChangeJson, typeId: string): R;
}

/**
 * Dispatches a type-tagged {@link AnyChangeJson} value to the handler of its concrete type.
 *
 * A type ID not known to this module is dispatched to {@link ChangeJsonVisitor.visitDefault}.
 */
export function visitChangeJson<R>(value: AnyChangeJson, visitor: ChangeJsonVisitor<R>): R {
	switch (value[0]) {
		case 'set': return visitor.visitUpdate(value[1] as UpdateJson);
		case 'Remove': return visitor.visitRemove(value[1] as RemoveJson);
		default: return visitor.visitDefault(value[1], value[0]);
	}
}

/**
 * Checks whether the given value is a type-tagged {@link AnyChangeJson} value: a tuple of a type ID and an object.
 *
 * Only the type ID and the shape of the tuple are checked, not the properties of the object.
 */
export function isAnyChangeJson(value: unknown): value is AnyChangeJson {
	return Array.isArray(value) && value.length === 2
		&& typeof value[0] === 'string'
		&& typeof value[1] === 'object' && value[1] !== null && !Array.isArray(value[1]);
}

/**
 * A local concrete type of the intermediate.
 */
export interface UpdateJson extends ChangeJson {
	value: string;
}

/**
 * Creates the type-tagged JSON representation of a {@link UpdateJson}.
 */
export function tagUpdate(self: UpdateJson): ['set', UpdateJson] {
	return ['set', self];
}

/**
 * Polymorphic collections of the open hierarchy.
 */
export interface LogJson {
	events: AnyEventJson[];

	latest: Record<string, AnyChangeJson>;
}
