// Generated by msgbuf from 'test/ts/graph/graph.proto'. Do not edit.
//
// Type definitions for the msgbuf JSON format of the protocol (types only, no runtime code).
//
// Note: The protocol uses 'option SharedGraph'. Its JSON format (objects as [type, id, {...}],
// references as object IDs, incremental updates) is not described by these types. No helper
// functions for polymorphic values are generated.

/**
 * Root of a hierarchy of a shared graph: no helpers.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface ElementJson {
	name: string;
}

/**
 * Polymorphic JSON representation of a {@link ElementJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyElementJson = ['Vertex', VertexJson];

/**
 * A concrete element.
 */
export interface VertexJson extends ElementJson {
	children: AnyElementJson[];
}
