/* Generated By:JavaCC: Do not edit this line. ProtobufParserTokenManager.java */
package de.haumacher.msgbuf.generator.parser;
import de.haumacher.msgbuf.generator.Util;
import de.haumacher.msgbuf.generator.ast.*;

/** Token Manager. */
public class ProtobufParserTokenManager implements ProtobufParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 31;
            return 34;
         }
         if ((active0 & 0x13ffe80L) != 0L)
         {
            jjmatchedKind = 31;
            return 29;
         }
         if ((active0 & 0x100L) != 0L)
         {
            jjmatchedKind = 31;
            return 67;
         }
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 31;
            return 92;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 31;
            return 50;
         }
         return -1;
      case 1:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 1;
            return 91;
         }
         if ((active0 & 0x177ff80L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 1;
            return 29;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 1;
            return 49;
         }
         if ((active0 & 0x80000L) != 0L)
            return 29;
         return -1;
      case 2:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 2;
            return 90;
         }
         if ((active0 & 0x100800L) != 0L)
            return 29;
         if ((active0 & 0x167f780L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 2;
            return 29;
         }
         if ((active0 & 0x800000L) != 0L)
            return 48;
         return -1;
      case 3:
         if ((active0 & 0x47f380L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 3;
            return 29;
         }
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 3;
            return 29;
         }
         if ((active0 & 0x1200400L) != 0L)
            return 29;
         return -1;
      case 4:
         if ((active0 & 0x207e380L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 4;
            return 29;
         }
         if ((active0 & 0x401000L) != 0L)
            return 29;
         return -1;
      case 5:
         if ((active0 & 0x2076280L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 5;
            return 29;
         }
         if ((active0 & 0x8100L) != 0L)
            return 29;
         return -1;
      case 6:
         if ((active0 & 0x2010280L) != 0L)
            return 29;
         if ((active0 & 0x66000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 6;
            return 29;
         }
         return -1;
      case 7:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 7;
            return 29;
         }
         if ((active0 & 0x62000L) != 0L)
            return 29;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 44:
         return jjStopAtPos(0, 37);
      case 46:
         return jjStopAtPos(0, 40);
      case 59:
         return jjStopAtPos(0, 34);
      case 60:
         return jjStopAtPos(0, 38);
      case 61:
         return jjStopAtPos(0, 33);
      case 62:
         return jjStopAtPos(0, 39);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x2000000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x10400L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x100a00L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x9000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x42000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x284000L);
      case 123:
         return jjStopAtPos(0, 35);
      case 125:
         return jjStopAtPos(0, 36);
      default :
         return jjMoveNfa_0(5, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x500880L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x42200L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x801400L);
      case 111:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(1, 19, 29);
         return jjMoveStringLiteralDfa2_0(active0, 0x3000000L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x204000L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x100L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x80L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000100L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 112:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(2, 11, 29);
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x60200L);
      case 116:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 23, 48);
         return jjMoveStringLiteralDfa3_0(active0, 0x18000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x200400L);
      case 120:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(2, 20, 29);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 21, 29);
         return jjMoveStringLiteralDfa4_0(active0, 0x52000L);
      case 103:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 29);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 107:
         return jjMoveStringLiteralDfa4_0(active0, 0x80L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 109:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 10, 29);
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x400200L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x20100L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x2380L);
      case 101:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(4, 22, 29);
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      case 102:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 29);
         break;
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x60000L);
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x2020000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L);
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x280L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000L);
      case 110:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 15, 29);
         break;
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000L);
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000L);
      case 120:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(5, 8, 29);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000L);
      case 101:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(6, 7, 29);
         else if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(6, 9, 29);
         return jjMoveStringLiteralDfa7_0(active0, 0x46000L);
      case 110:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(6, 25, 29);
         break;
      case 115:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(6, 16, 29);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(7, 13, 29);
         else if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(7, 18, 29);
         break;
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000L);
      case 116:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(7, 17, 29);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 116:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(8, 14, 29);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 118;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 67:
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAdd(29);
                  break;
               case 91:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAdd(29);
                  break;
               case 5:
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 27)
                        kind = 27;
                     jjCheckNAddTwoStates(10, 7);
                  }
                  else if (curChar == 47)
                     jjAddStates(0, 4);
                  else if (curChar == 34)
                     jjCheckNAddStates(5, 7);
                  else if (curChar == 39)
                     jjCheckNAddStates(8, 10);
                  else if (curChar == 48)
                  {
                     if (kind > 27)
                        kind = 27;
                     jjCheckNAdd(7);
                  }
                  break;
               case 92:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAdd(29);
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAdd(29);
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 54)
                     jjCheckNAdd(41);
                  else if (curChar == 51)
                     jjCheckNAdd(35);
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAdd(29);
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAdd(29);
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAdd(29);
                  break;
               case 6:
                  if (curChar != 48)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAdd(7);
                  break;
               case 7:
                  if (curChar == 46)
                     jjCheckNAdd(8);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAdd(8);
                  break;
               case 9:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddTwoStates(10, 7);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddTwoStates(10, 7);
                  break;
               case 11:
               case 16:
                  if (curChar == 39)
                     jjCheckNAddStates(8, 10);
                  break;
               case 12:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddStates(8, 10);
                  break;
               case 13:
                  if (curChar == 39 && kind > 28)
                     kind = 28;
                  break;
               case 15:
                  if (curChar == 34)
                     jjCheckNAddStates(8, 10);
                  break;
               case 18:
               case 22:
                  if (curChar == 34)
                     jjCheckNAddStates(5, 7);
                  break;
               case 19:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 20:
                  if (curChar == 34 && kind > 28)
                     kind = 28;
                  break;
               case 23:
                  if (curChar == 39)
                     jjCheckNAddStates(5, 7);
                  break;
               case 26:
                  jjAddStates(11, 12);
                  break;
               case 35:
                  if (curChar == 50 && kind > 26)
                     kind = 26;
                  break;
               case 36:
               case 55:
               case 64:
               case 68:
                  if (curChar == 51)
                     jjCheckNAdd(35);
                  break;
               case 41:
                  if (curChar == 52 && kind > 26)
                     kind = 26;
                  break;
               case 42:
               case 59:
               case 74:
               case 78:
                  if (curChar == 54)
                     jjCheckNAdd(41);
                  break;
               case 51:
                  if (curChar == 54)
                     jjCheckNAdd(41);
                  break;
               case 97:
                  if (curChar == 47)
                     jjAddStates(0, 4);
                  break;
               case 98:
                  if (curChar == 42)
                     jjCheckNAdd(99);
                  break;
               case 99:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 100:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 101:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 102:
                  if (curChar == 47 && kind > 5)
                     kind = 5;
                  break;
               case 103:
               case 104:
                  if (curChar == 42)
                     jjCheckNAdd(102);
                  break;
               case 105:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 47)
                     jjCheckNAddTwoStates(107, 108);
                  break;
               case 107:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(107, 108);
                  break;
               case 108:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 109:
                  if (curChar == 42)
                     jjCheckNAddStates(16, 18);
                  break;
               case 110:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddStates(16, 18);
                  break;
               case 111:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 112:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddStates(16, 18);
                  break;
               case 113:
                  if (curChar == 47 && kind > 32)
                     kind = 32;
                  break;
               case 114:
               case 116:
                  if (curChar == 42)
                     jjCheckNAdd(113);
                  break;
               case 115:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 117:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 67:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 87;
                  else if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 82;
                  else if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 76;
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 72;
                  else if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 91:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 5:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                     jjCheckNAdd(29);
                  }
                  else if (curChar == 96)
                     jjCheckNAdd(26);
                  if (curChar == 98)
                     jjAddStates(19, 20);
                  else if (curChar == 115)
                     jjAddStates(21, 25);
                  else if (curChar == 117)
                     jjAddStates(26, 27);
                  else if (curChar == 105)
                     jjAddStates(28, 29);
                  else if (curChar == 102)
                     jjAddStates(30, 32);
                  else if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 92:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 95;
                  else if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 49:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 51;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
               case 29:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAdd(29);
                  break;
               case 50:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 52;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 90:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 108)
                  {
                     if (kind > 26)
                        kind = 26;
                  }
                  break;
               case 34:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 45;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 33;
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 0:
                  if (curChar == 101 && kind > 26)
                     kind = 26;
                  break;
               case 1:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 2:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 12:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(8, 10);
                  break;
               case 14:
                  if (curChar == 92)
                     jjAddStates(33, 35);
                  break;
               case 17:
                  if (curChar == 92)
                     jjCheckNAddStates(8, 10);
                  break;
               case 19:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 21:
                  if (curChar == 92)
                     jjAddStates(36, 38);
                  break;
               case 24:
                  if (curChar == 92)
                     jjCheckNAddStates(5, 7);
                  break;
               case 25:
                  if (curChar == 96)
                     jjCheckNAdd(26);
                  break;
               case 26:
                  if ((0xfffffffeffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(26, 27);
                  break;
               case 27:
                  if (curChar == 96 && kind > 29)
                     kind = 29;
                  break;
               case 28:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAdd(29);
                  break;
               case 30:
                  if (curChar == 102)
                     jjAddStates(30, 32);
                  break;
               case 31:
                  if (curChar == 116 && kind > 26)
                     kind = 26;
                  break;
               case 32:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 37:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 43:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 105)
                     jjAddStates(28, 29);
                  break;
               case 52:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 117)
                     jjAddStates(26, 27);
                  break;
               case 56:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 60:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if (curChar == 115)
                     jjAddStates(21, 25);
                  break;
               case 65:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 69:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 75:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 79:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 103 && kind > 26)
                     kind = 26;
                  break;
               case 85:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 98)
                     jjAddStates(19, 20);
                  break;
               case 93:
                  if (curChar == 115 && kind > 26)
                     kind = 26;
                  break;
               case 94:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 95:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 99:
               case 101:
                  jjCheckNAddStates(13, 15);
                  break;
               case 107:
                  jjAddStates(39, 40);
                  break;
               case 110:
               case 112:
                  jjCheckNAddStates(16, 18);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 12:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(8, 10);
                  break;
               case 19:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(5, 7);
                  break;
               case 26:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(11, 12);
                  break;
               case 99:
               case 101:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(13, 15);
                  break;
               case 107:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(39, 40);
                  break;
               case 110:
               case 112:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(16, 18);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 118 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   98, 105, 106, 115, 117, 19, 20, 21, 12, 13, 14, 26, 27, 99, 100, 103, 
   110, 111, 114, 92, 96, 67, 73, 77, 83, 88, 58, 62, 50, 53, 34, 40, 
   46, 15, 16, 17, 22, 23, 24, 107, 108, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\160\141\143\153\141\147\145", 
"\163\171\156\164\141\170", "\155\145\163\163\141\147\145", "\145\156\165\155", "\155\141\160", 
"\157\156\145\157\146", "\162\145\160\145\141\164\145\144", "\164\162\141\156\163\151\145\156\164", 
"\157\160\164\151\157\156", "\145\170\164\145\156\144\163", "\141\142\163\164\162\141\143\164", 
"\162\145\163\145\162\166\145\144", "\164\157", "\155\141\170", "\164\162\165\145", "\146\141\154\163\145", 
"\151\156\164", "\154\157\156\147", "\142\157\157\154\145\141\156", null, null, null, null, 
null, null, null, "\75", "\73", "\173", "\175", "\54", "\74", "\76", "\56", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x1ffbfffff81L, 
};
static final long[] jjtoSkip = {
   0x7eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[118];
private final int[] jjstateSet = new int[236];
protected char curChar;
/** Constructor. */
public ProtobufParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public ProtobufParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 118; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
