// Generated by msgbuf from 'test/ts/common/common.proto'. Do not edit.
//
// Type definitions for the msgbuf JSON format of the protocol (types only, no runtime code).

/**
 * Common types, documented at the package declaration.
 *
 * @packageDocumentation
 */

/**
 * Display modes of a button.
 */
export type DisplayModeJson =
	/**
	 * Only the icon is shown.
	 */
	| 'icon-only'
	/**
	 * Only the label is shown.
	 */
	| 'label-only'
	/**
	 * Constant without custom name, combines `'icon-only'` and `'label-only'`.
	 */
	| 'BOTH';

/**
 * A point in the plane.
 */
export interface PointJson {
	/**
	 * The X coordinate.
	 */
	x: number;

	/**
	 * The Y coordinate.
	 */
	y: number;
}

/**
 * Abstract base of a polymorphic hierarchy with an abstract root.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface NodeJson {
	/**
	 * The node ID.
	 */
	id: string;
}

/**
 * Polymorphic JSON representation of a {@link NodeJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyNodeJson = ['Leaf', LeafJson] | ['Inner', InnerJson];

/**
 * A leaf node.
 */
export interface LeafJson extends NodeJson {
	/**
	 * The value.
	 */
	value: number;
}

/**
 * An inner node.
 */
export interface InnerJson extends NodeJson {
	/**
	 * The children, written as type-tagged tuples.
	 */
	children: AnyNodeJson[];
}
