// Generated by msgbuf from 'test/ts/common/common.proto'. Do not edit.
//
// Type definitions for the msgbuf JSON format of the protocol, and helper functions for its
// type-tagged polymorphic values (visitor dispatch, tagging, tag guards).

/**
 * Common types, documented at the package declaration.
 *
 * @packageDocumentation
 */

/**
 * Display modes of a button.
 */
export type DisplayModeJson =
	/**
	 * Only the icon is shown.
	 */
	| 'icon-only'
	/**
	 * Only the label is shown.
	 */
	| 'label-only'
	/**
	 * Constant without custom name, combines `'icon-only'` and `'label-only'`.
	 */
	| 'BOTH';

/**
 * A point in the plane.
 */
export interface PointJson {
	/**
	 * The X coordinate.
	 */
	x: number;

	/**
	 * The Y coordinate.
	 */
	y: number;
}

/**
 * Abstract base of a polymorphic hierarchy with an abstract root.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface NodeJson {
	/**
	 * The node ID.
	 */
	id: string;
}

/**
 * Polymorphic JSON representation of a {@link NodeJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyNodeJson = ['Leaf', LeafJson] | ['Inner', InnerJson];

/**
 * Handlers for all concrete types of {@link NodeJson}.
 */
export interface NodeJsonVisitor<R> {
	/**
	 * Handles a {@link LeafJson}.
	 */
	visitLeaf(self: LeafJson): R;

	/**
	 * Handles a {@link InnerJson}.
	 */
	visitInner(self: InnerJson): R;
}

/**
 * Dispatches a type-tagged {@link AnyNodeJson} value to the handler of its concrete type.
 *
 * @throws Error if the type ID is not known.
 */
export function visitNodeJson<R>(value: AnyNodeJson, visitor: NodeJsonVisitor<R>): R {
	switch (value[0]) {
		case 'Leaf': return visitor.visitLeaf(value[1]);
		case 'Inner': return visitor.visitInner(value[1]);
		default: {
			const unknownType: never = value[0];
			throw new Error('Unknown type ID: ' + unknownType);
		}
	}
}

/**
 * Checks whether the given value is a type-tagged {@link AnyNodeJson} value: a tuple of a known type ID and an object.
 *
 * Only the type ID and the shape of the tuple are checked, not the properties of the object.
 */
export function isAnyNodeJson(value: unknown): value is AnyNodeJson {
	return Array.isArray(value) && value.length === 2
		&& (value[0] === 'Leaf' || value[0] === 'Inner')
		&& typeof value[1] === 'object' && value[1] !== null && !Array.isArray(value[1]);
}

/**
 * A leaf node.
 */
export interface LeafJson extends NodeJson {
	/**
	 * The value.
	 */
	value: number;
}

/**
 * Creates the type-tagged JSON representation of a {@link LeafJson}.
 */
export function tagLeaf(self: LeafJson): ['Leaf', LeafJson] {
	return ['Leaf', self];
}

/**
 * An inner node.
 */
export interface InnerJson extends NodeJson {
	/**
	 * The children, written as type-tagged tuples.
	 */
	children: AnyNodeJson[];
}

/**
 * Creates the type-tagged JSON representation of a {@link InnerJson}.
 */
export function tagInner(self: InnerJson): ['Inner', InnerJson] {
	return ['Inner', self];
}
