/* Generated By:JavaCC: Do not edit this line. ProtobufParserConstants.java */
package de.haumacher.msgbuf.generator.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProtobufParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int TAB = 2;
  /** RegularExpression Id. */
  int CR = 3;
  /** RegularExpression Id. */
  int NL = 4;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 5;
  /** RegularExpression Id. */
  int LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int DOC_COMMENT = 7;
  /** RegularExpression Id. */
  int PACKAGE = 8;
  /** RegularExpression Id. */
  int IMPORT = 9;
  /** RegularExpression Id. */
  int SYNTAX = 10;
  /** RegularExpression Id. */
  int MESSAGE = 11;
  /** RegularExpression Id. */
  int ENUM = 12;
  /** RegularExpression Id. */
  int MAP = 13;
  /** RegularExpression Id. */
  int ONEOF = 14;
  /** RegularExpression Id. */
  int REPEATED = 15;
  /** RegularExpression Id. */
  int TRANSIENT = 16;
  /** RegularExpression Id. */
  int OPTION = 17;
  /** RegularExpression Id. */
  int EXTENDS = 18;
  /** RegularExpression Id. */
  int ABSTRACT = 19;
  /** RegularExpression Id. */
  int RESERVED = 20;
  /** RegularExpression Id. */
  int TO = 21;
  /** RegularExpression Id. */
  int MAX = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int NULL = 25;
  /** RegularExpression Id. */
  int INT_TYPE = 26;
  /** RegularExpression Id. */
  int LONG_TYPE = 27;
  /** RegularExpression Id. */
  int BOOLEAN_TYPE = 28;
  /** RegularExpression Id. */
  int JSON_TYPE = 29;
  /** RegularExpression Id. */
  int TYPE = 30;
  /** RegularExpression Id. */
  int INT = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;
  /** RegularExpression Id. */
  int STRING = 33;
  /** RegularExpression Id. */
  int XNAME = 34;
  /** RegularExpression Id. */
  int QUOTE = 35;
  /** RegularExpression Id. */
  int NAME = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<BLOCK_COMMENT>",
    "<LINE_COMMENT>",
    "<DOC_COMMENT>",
    "\"package\"",
    "\"import\"",
    "\"syntax\"",
    "\"message\"",
    "\"enum\"",
    "\"map\"",
    "\"oneof\"",
    "\"repeated\"",
    "\"transient\"",
    "\"option\"",
    "\"extends\"",
    "\"abstract\"",
    "\"reserved\"",
    "\"to\"",
    "\"max\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"int\"",
    "\"long\"",
    "\"boolean\"",
    "\"json\"",
    "<TYPE>",
    "<INT>",
    "<NUMBER>",
    "<STRING>",
    "<XNAME>",
    "<QUOTE>",
    "<NAME>",
    "\"=\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"@\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"<\"",
    "\">\"",
    "\".\"",
  };

}
