// Generated by msgbuf from 'test/ts/shapes/shapes.proto'. Do not edit.
//
// Type definitions for the msgbuf JSON format of the protocol (types only, no runtime code).

/**
 * Shapes and button states for testing the TypeScript generator.
 *
 * <p>See {@link ButtonState}, {@link Group.shapes the shapes of a group} and `nothing`.</p>
 *
 * @packageDocumentation
 */

import type { Point as common_Point, DisplayMode, AnyNode } from '../common/common';

/**
 * A local point clashing with the imported one.
 */
export interface Point {
	/**
	 * A coordinate pair.
	 */
	value?: common_Point;
}

/**
 * A label.
 */
export interface Label {
	text?: string;
}

/**
 * State of a button.
 *
 * <p>Refers to {@link Label}.</p>
 */
export interface ButtonState {
	/**
	 * The label.
	 */
	label?: string;

	/**
	 * Whether the button is disabled, see {@link ButtonState.label} and {@link ButtonState.label the label}.
	 *
	 * Code: `if (x) { y(); }`, literal: a<b, unknown tag {@value #size}.
	 */
	disabled?: boolean;

	/**
	 * How the button is displayed, e.g. `'icon-only'` or
	 * only the label, see {@link DisplayMode}.
	 */
	mode?: DisplayMode;

	/**
	 * A property whose JSON name is not an identifier: `data-key`, unlike
	 * `cache`, `unknown()` and `String`.
	 */
	'data-key'?: string;

	/**
	 * A number with default value.
	 *
	 * @defaultValue 13
	 */
	size?: number;

	/**
	 * A 64 bit number.
	 */
	timestamp?: number;

	/**
	 * A float.
	 */
	ratio?: number;

	/**
	 * Binary data (Base64).
	 */
	data?: string;

	/**
	 * Arbitrary JSON.
	 */
	extra?: unknown;

	/**
	 * Optional nested message.
	 */
	caption?: Label;

	/**
	 * Tags.
	 */
	tags?: string[];

	/**
	 * Labels by key.
	 */
	labels?: Record<string, Label>;

	/**
	 * Ratings by number.
	 */
	ratings?: Array<{ key: number; value: string }>;

	/**
	 * A polymorphic reference to another file.
	 */
	root?: AnyNode;

	/**
	 * Local points, see {@link Point.value} and {@link common_Point.x}, inherited {@link Shape.origin}.
	 */
	points?: Point[];
}

/**
 * Concrete base class: JSON has no type information.
 */
export interface Base {
	name?: string;
}

/**
 * Specialization of a concrete base.
 */
export interface Derived extends Base {
	extra?: number;
}

/**
 * Abstract shape.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface Shape {
	/**
	 * The origin.
	 */
	origin?: common_Point;
}

/**
 * Polymorphic JSON representation of a {@link Shape}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyShape = ['Rectangle', Rectangle] | ['Group', Group] | ['circle', Circle];

/**
 * Abstract intermediate class.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface Rounded extends Shape {}

/**
 * Polymorphic JSON representation of a {@link Rounded}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyRounded = ['circle', Circle];

/**
 * A circle.
 */
export interface Circle extends Rounded {
	/**
	 * The radius.
	 */
	r?: number;
}

/**
 * A rectangle.
 */
export interface Rectangle extends Shape {
	width?: number;

	height?: number;
}

/**
 * A group of shapes.
 */
export interface Group extends Shape {
	/**
	 * Contents written polymorphically.
	 */
	shapes?: AnyShape[];

	/**
	 * Monomorphic reference to a concrete type in a hierarchy.
	 */
	main?: Circle;

	/**
	 * Reference to an abstract intermediate type.
	 */
	rounded?: AnyRounded;

	info?: Group.Info;
}

export namespace Group {
	/**
	 * A label local to groups.
	 */
	export interface Label {
		kind?: Group.Label.Kind;
	}

	export namespace Label {
		/**
		 * Group label kind.
		 */
		export type Kind =
			| 'PRIMARY'
			| 'SECONDARY';
	}

	/**
	 * Nested message referencing the shadowed top-level type {@link __Label} and {@link Group.Label}.
	 */
	export interface Info {
		/**
		 * The top-level label.
		 */
		global?: __Label;

		/**
		 * The nested label.
		 */
		local?: Group.Label;
	}
}

/**
 * An empty enum.
 */
export type Nothing = never;

type __Label = Label;
