// Generated by msgbuf from 'test/ts/shapes/shapes.proto'. Do not edit.
//
// Type definitions for the msgbuf JSON format of the protocol, and helper functions for its
// type-tagged polymorphic values (visitor dispatch, tagging, tag guards).

/**
 * Shapes and button states for testing the TypeScript generator.
 *
 * <p>See {@link ButtonStateJson}, {@link GroupJson.shapes the shapes of a group} and `nothing`.</p>
 *
 * @packageDocumentation
 */

import type { PointJson as common_PointJson, DisplayModeJson, AnyNodeJson } from '../common/common';

/**
 * A local point clashing with the imported one.
 */
export interface PointJson {
	/**
	 * A coordinate pair.
	 */
	value?: common_PointJson;
}

/**
 * A label.
 */
export interface LabelJson {
	text: string;
}

/**
 * State of a button.
 *
 * <p>Refers to {@link LabelJson}.</p>
 */
export interface ButtonStateJson {
	/**
	 * The label.
	 */
	label: string;

	/**
	 * Whether the button is disabled, see {@link ButtonStateJson.label} and {@link ButtonStateJson.label the label}.
	 *
	 * Code: `if (x) { y(); }`, literal: a<b, unknown tag {@value #size}.
	 */
	disabled: boolean;

	/**
	 * How the button is displayed, e.g. `'icon-only'` or
	 * only the label, see {@link DisplayModeJson}.
	 */
	mode: DisplayModeJson;

	/**
	 * A property whose JSON name is not an identifier: `data-key`, unlike
	 * `cache`, `unknown()` and `String`.
	 */
	'data-key': string;

	/**
	 * A number with default value.
	 *
	 * @defaultValue 13
	 */
	size: number;

	/**
	 * A 64 bit number.
	 */
	timestamp: number;

	/**
	 * A float.
	 */
	ratio: number;

	/**
	 * Binary data (Base64).
	 */
	data: string | null;

	/**
	 * Arbitrary JSON.
	 */
	extra?: unknown;

	/**
	 * Optional nested message.
	 */
	caption?: LabelJson;

	/**
	 * Optional string, omitted when not set.
	 */
	hint?: string;

	/**
	 * Tags.
	 */
	tags: string[];

	/**
	 * Labels by key.
	 */
	labels: Record<string, LabelJson>;

	/**
	 * Ratings by number.
	 */
	ratings: Array<{ key: number; value: string }>;

	/**
	 * A polymorphic reference to another file.
	 */
	root?: AnyNodeJson;

	/**
	 * Local points, see {@link PointJson.value} and {@link common_PointJson.x}, inherited {@link ShapeJson.origin}.
	 */
	points: PointJson[];
}

/**
 * Concrete base class: JSON has no type information.
 */
export interface BaseJson {
	name: string;
}

/**
 * Specialization of a concrete base.
 */
export interface DerivedJson extends BaseJson {
	extra: number;
}

/**
 * Abstract shape.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface ShapeJson {
	/**
	 * The origin.
	 */
	origin?: common_PointJson;
}

/**
 * Polymorphic JSON representation of a {@link ShapeJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyShapeJson = ['Rectangle', RectangleJson] | ['Group', GroupJson] | ['circle', CircleJson];

/**
 * Handlers for all concrete types of {@link ShapeJson}.
 */
export interface ShapeJsonVisitor<R> {
	/**
	 * Handles a {@link RectangleJson}.
	 */
	visitRectangle(self: RectangleJson): R;

	/**
	 * Handles a {@link GroupJson}.
	 */
	visitGroup(self: GroupJson): R;

	/**
	 * Handles a {@link CircleJson}.
	 */
	visitCircle(self: CircleJson): R;
}

/**
 * Dispatches a type-tagged {@link AnyShapeJson} value to the handler of its concrete type.
 *
 * @throws Error if the type ID is not known.
 */
export function visitShapeJson<R>(value: AnyShapeJson, visitor: ShapeJsonVisitor<R>): R {
	switch (value[0]) {
		case 'Rectangle': return visitor.visitRectangle(value[1]);
		case 'Group': return visitor.visitGroup(value[1]);
		case 'circle': return visitor.visitCircle(value[1]);
		default: {
			const unknownType: never = value[0];
			throw new Error('Unknown type ID: ' + unknownType);
		}
	}
}

/**
 * Checks whether the given value is a type-tagged {@link AnyShapeJson} value: a tuple of a known type ID and an object.
 *
 * Only the type ID and the shape of the tuple are checked, not the properties of the object.
 */
export function isAnyShapeJson(value: unknown): value is AnyShapeJson {
	return Array.isArray(value) && value.length === 2
		&& (value[0] === 'Rectangle' || value[0] === 'Group' || value[0] === 'circle')
		&& typeof value[1] === 'object' && value[1] !== null && !Array.isArray(value[1]);
}

/**
 * Abstract intermediate class.
 *
 * Abstract type, the properties are only present in the JSON of its concrete specializations.
 */
export interface RoundedJson extends ShapeJson {}

/**
 * Polymorphic JSON representation of a {@link RoundedJson}: a tuple of the type ID and the properties of a concrete type.
 */
export type AnyRoundedJson = ['circle', CircleJson];

/**
 * Handlers for all concrete types of {@link RoundedJson}.
 */
export interface RoundedJsonVisitor<R> {
	/**
	 * Handles a {@link CircleJson}.
	 */
	visitCircle(self: CircleJson): R;
}

/**
 * Dispatches a type-tagged {@link AnyRoundedJson} value to the handler of its concrete type.
 *
 * @throws Error if the type ID is not known.
 */
export function visitRoundedJson<R>(value: AnyRoundedJson, visitor: RoundedJsonVisitor<R>): R {
	switch (value[0]) {
		case 'circle': return visitor.visitCircle(value[1]);
		default: {
			const unknownType: never = value[0];
			throw new Error('Unknown type ID: ' + unknownType);
		}
	}
}

/**
 * Checks whether the given value is a type-tagged {@link AnyRoundedJson} value: a tuple of a known type ID and an object.
 *
 * Only the type ID and the shape of the tuple are checked, not the properties of the object.
 */
export function isAnyRoundedJson(value: unknown): value is AnyRoundedJson {
	return Array.isArray(value) && value.length === 2
		&& value[0] === 'circle'
		&& typeof value[1] === 'object' && value[1] !== null && !Array.isArray(value[1]);
}

/**
 * A circle.
 */
export interface CircleJson extends RoundedJson {
	/**
	 * The radius.
	 */
	r: number;
}

/**
 * Creates the type-tagged JSON representation of a {@link CircleJson}.
 */
export function tagCircle(self: CircleJson): ['circle', CircleJson] {
	return ['circle', self];
}

/**
 * A rectangle.
 */
export interface RectangleJson extends ShapeJson {
	width: number;

	height: number;
}

/**
 * Creates the type-tagged JSON representation of a {@link RectangleJson}.
 */
export function tagRectangle(self: RectangleJson): ['Rectangle', RectangleJson] {
	return ['Rectangle', self];
}

/**
 * A group of shapes.
 */
export interface GroupJson extends ShapeJson {
	/**
	 * Contents written polymorphically.
	 */
	shapes: AnyShapeJson[];

	/**
	 * Monomorphic reference to a concrete type in a hierarchy.
	 */
	main?: CircleJson;

	/**
	 * Reference to an abstract intermediate type.
	 */
	rounded?: AnyRoundedJson;

	info?: GroupJson.Info;
}

export namespace GroupJson {
	/**
	 * A label local to groups.
	 */
	export interface Label {
		kind: GroupJson.Label.Kind;
	}

	export namespace Label {
		/**
		 * Group label kind.
		 */
		export type Kind =
			| 'PRIMARY'
			| 'SECONDARY';
	}

	/**
	 * Nested message whose name clashes with the TypeScript name of the top-level {@link __LabelJson}.
	 */
	export interface LabelJson {}

	/**
	 * Nested message referencing the shadowed top-level type {@link __LabelJson} and {@link GroupJson.Label}.
	 */
	export interface Info {
		/**
		 * The top-level label.
		 */
		global?: __LabelJson;

		/**
		 * The nested label.
		 */
		local?: GroupJson.Label;
	}
}

/**
 * Creates the type-tagged JSON representation of a {@link GroupJson}.
 */
export function tagGroup(self: GroupJson): ['Group', GroupJson] {
	return ['Group', self];
}

/**
 * An empty enum.
 */
export type NothingJson = never;

type __LabelJson = LabelJson;
